basic_settings:
  site_title: Alex Dixon
  site_tagline: Welcome to my programming blog and portfolio, I have worked in gamedev for over 10 years and I am currently principal programmer at Flavourworks. I enjoy shuffling bytes and swizzling vectors...   
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'WebGL Demos'
      url: 'webgl-demos'
    - title: 'Releases'
      url: 'releases'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  github_url: 'https://github.com/polymonster'
  twitter_url: 'https://twitter.com/polymonster'
  linkedin_url: 'https://www.linkedin.com/in/alexdixon1611/'
  instagram_url: 'https://instagram.com/__shufb'
  reddit_url: 'https://www.reddit.com/user/__shufb'
  youtube_url: 'https://www.youtube.com/channel/UCQRmui5w4Urz-h4P9CL7rmA'
  envelope_fas: 'mailto:alexandercdixon@gmail.com'
  rss_fas: 'https://polymonster.github.io/feed'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#A2DED0'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Rubik:300,400|Muli:400,400i,600" rel="stylesheet">'
  title_font: '"Rubik", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
